# Generated by Django 4.0 on 2024-04-21 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choices',
            old_name='Gender',
            new_name='Data',
        ),
    ]
