# Generated by Django 4.0 on 2024-04-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0002_rename_gender_choices_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choices',
            name='Data',
            field=models.CharField(choices=[(0, 'some')], max_length=1),
        ),
    ]
