# Generated by Django 4.0 on 2024-04-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0003_alter_choices_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choices',
            name='Data',
            field=models.CharField(choices=[('0', 'thing')], max_length=1),
        ),
    ]
