# Generated by Django 4.0 on 2024-04-21 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0004_alter_choices_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choices',
        ),
    ]
